# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OtGE5dSambrYxvlTsuwECYnKA_E2fibz

Rais quadada: $\sqrt{3^2}=3$

## Text cells
This is a **text cell**. You can **double-click** to edit this cell. Text cells
use markdown syntax. To learn more, see our [markdown
guide](/notebooks/markdown_guide.ipynb).

You can also add math to text cells using [LaTeX](http://www.latex-project.org/)
to be rendered by [MathJax](https://www.mathjax.org). Just place the statement
within a pair of **\$** signs. For example `$\sqrt{3x-1}+(1+x)^2$` becomes
$\sqrt{3x-1}+(1+x)^2.$
"""

import math
print('Feito no colab notebook 1')
print('**************************')
print('v1 = math.sqrt(3^2)')
v0=3**2
print(v0)
print('v1 = math.sqrt(3**2)')
v1 = math.sqrt(3**2)
print(v1)
#v1=sqrt{3^2}
print('v2=math.sqrt(16)')
v2=math.sqrt(16)
print(v2)

print('****************')
print('v3 = 9 ** 0.5')
v3 = 9 ** 0.5
print(v3)
print(v3)

print('****************')
print('v3 = 9 ** 0.5')

"""xxxxxxxxxxxxxxx

"""